// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIssueComment = `-- name: CreateIssueComment :one
INSERT INTO issue_comments (issue_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateIssueCommentParams struct {
	IssueID  uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

func (q *Queries) CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createIssueComment, arg.IssueID, arg.AuthorID, arg.Body)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteIssueComment = `-- name: DeleteIssueComment :exec
DELETE FROM issue_comments
WHERE issue_id = $1 AND id = $2
`

type DeleteIssueCommentParams struct {
	IssueID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) DeleteIssueComment(ctx context.Context, arg DeleteIssueCommentParams) error {
	_, err := q.db.Exec(ctx, deleteIssueComment, arg.IssueID, arg.ID)
	return err
}

const getIssueComment = `-- name: GetIssueComment :one
SELECT c.id, c.issue_id, c.author_id, u.name AS author_name, c.body, c.created_at, c.updated_at
FROM issue_comments c
JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1 AND c.id = $2
`

type GetIssueCommentParams struct {
	IssueID uuid.UUID
	ID      uuid.UUID
}

type GetIssueCommentRow struct {
	ID         uuid.UUID
	IssueID    uuid.UUID
	AuthorID   uuid.UUID
	AuthorName string
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetIssueComment(ctx context.Context, arg GetIssueCommentParams) (GetIssueCommentRow, error) {
	row := q.db.QueryRow(ctx, getIssueComment, arg.IssueID, arg.ID)
	var i GetIssueCommentRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT c.id, c.issue_id, c.author_id, u.name AS author_name, c.body, c.created_at, c.updated_at
FROM issue_comments c
JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC, c.id ASC
`

type ListIssueCommentsRow struct {
	ID         uuid.UUID
	IssueID    uuid.UUID
	AuthorID   uuid.UUID
	AuthorName string
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListIssueComments(ctx context.Context, issueID uuid.UUID) ([]ListIssueCommentsRow, error) {
	rows, err := q.db.Query(ctx, listIssueComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueCommentsRow
	for rows.Next() {
		var i ListIssueCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueComment = `-- name: UpdateIssueComment :exec
UPDATE issue_comments
SET body = $3, updated_at = now()
WHERE issue_id = $1 AND id = $2
`

type UpdateIssueCommentParams struct {
	IssueID uuid.UUID
	ID      uuid.UUID
	Body    string
}

func (q *Queries) UpdateIssueComment(ctx context.Context, arg UpdateIssueCommentParams) error {
	_, err := q.db.Exec(ctx, updateIssueComment, arg.IssueID, arg.ID, arg.Body)
	return err
}
