// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptWorkspaceInvite = `-- name: AcceptWorkspaceInvite :execrows
UPDATE workspace_invites
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) AcceptWorkspaceInvite(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, acceptWorkspaceInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWorkspaceInvite = `-- name: CreateWorkspaceInvite :one
INSERT INTO workspace_invites (workspace_id, email, role, token_hash, created_by_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, role, token_hash, created_by_user_id, expires_at, accepted_at, revoked_at, created_at
`

type CreateWorkspaceInviteParams struct {
	WorkspaceID     uuid.UUID
	Email           string
	Role            WorkspaceRole
	TokenHash       []byte
	CreatedByUserID uuid.UUID
	ExpiresAt       time.Time
}

func (q *Queries) CreateWorkspaceInvite(ctx context.Context, arg CreateWorkspaceInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceInviteByTokenHashForUpdate = `-- name: GetWorkspaceInviteByTokenHashForUpdate :one
SELECT id, workspace_id, email, role, token_hash, created_by_user_id, expires_at, accepted_at, revoked_at, created_at
FROM workspace_invites
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetWorkspaceInviteByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInviteByTokenHashForUpdate, tokenHash)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOpenWorkspaceInvites = `-- name: ListOpenWorkspaceInvites :many
SELECT wi.id, wi.workspace_id, wi.email, wi.role, wi.created_by_user_id, creator.name AS created_by_name, wi.expires_at, wi.created_at
FROM workspace_invites AS wi
JOIN users AS creator ON creator.id = wi.created_by_user_id
WHERE wi.workspace_id = $1 AND wi.accepted_at IS NULL AND wi.revoked_at IS NULL AND wi.expires_at > now()
ORDER BY wi.created_at DESC, wi.id DESC
`

type ListOpenWorkspaceInvitesRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Email           string
	Role            WorkspaceRole
	CreatedByUserID uuid.UUID
	CreatedByName   string
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

func (q *Queries) ListOpenWorkspaceInvites(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenWorkspaceInvitesRow, error) {
	rows, err := q.db.Query(ctx, listOpenWorkspaceInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenWorkspaceInvitesRow
	for rows.Next() {
		var i ListOpenWorkspaceInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWorkspaceInvitesByCreator = `-- name: ListOpenWorkspaceInvitesByCreator :many
SELECT wi.id, wi.workspace_id, wi.email, wi.role, wi.created_by_user_id, creator.name AS created_by_name, wi.expires_at, wi.created_at
FROM workspace_invites AS wi
JOIN users AS creator ON creator.id = wi.created_by_user_id
WHERE wi.workspace_id = $1 AND wi.created_by_user_id = $2 AND wi.accepted_at IS NULL AND wi.revoked_at IS NULL AND wi.expires_at > now()
ORDER BY wi.created_at DESC, wi.id DESC
`

type ListOpenWorkspaceInvitesByCreatorParams struct {
	WorkspaceID     uuid.UUID
	CreatedByUserID uuid.UUID
}

type ListOpenWorkspaceInvitesByCreatorRow struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Email           string
	Role            WorkspaceRole
	CreatedByUserID uuid.UUID
	CreatedByName   string
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

func (q *Queries) ListOpenWorkspaceInvitesByCreator(ctx context.Context, arg ListOpenWorkspaceInvitesByCreatorParams) ([]ListOpenWorkspaceInvitesByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listOpenWorkspaceInvitesByCreator, arg.WorkspaceID, arg.CreatedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenWorkspaceInvitesByCreatorRow
	for rows.Next() {
		var i ListOpenWorkspaceInvitesByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOpenWorkspaceInvitesForEmail = `-- name: RevokeOpenWorkspaceInvitesForEmail :exec
UPDATE workspace_invites
SET revoked_at = now()
WHERE workspace_id = $1 AND email = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeOpenWorkspaceInvitesForEmailParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) RevokeOpenWorkspaceInvitesForEmail(ctx context.Context, arg RevokeOpenWorkspaceInvitesForEmailParams) error {
	_, err := q.db.Exec(ctx, revokeOpenWorkspaceInvitesForEmail, arg.WorkspaceID, arg.Email)
	return err
}

const revokeWorkspaceInvite = `-- name: RevokeWorkspaceInvite :execrows
UPDATE workspace_invites
SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeWorkspaceInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RevokeWorkspaceInvite(ctx context.Context, arg RevokeWorkspaceInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWorkspaceInvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeWorkspaceInviteByCreator = `-- name: RevokeWorkspaceInviteByCreator :execrows
UPDATE workspace_invites
SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2 AND created_by_user_id = $3 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeWorkspaceInviteByCreatorParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	CreatedByUserID uuid.UUID
}

func (q *Queries) RevokeWorkspaceInviteByCreator(ctx context.Context, arg RevokeWorkspaceInviteByCreatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWorkspaceInviteByCreator, arg.ID, arg.WorkspaceID, arg.CreatedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
