// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (project_id, title, description, status, priority, creator_id, assignee_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
`

type CreateIssueParams struct {
	ProjectID   uuid.UUID
	Title       string
	Description string
	Status      string
	Priority    string
	CreatorID   uuid.UUID
	AssigneeID  pgtype.UUID
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.CreatorID,
		arg.AssigneeID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatorID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
FROM issues
WHERE project_id = $1 AND id = $2
`

type GetIssueParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ProjectID, arg.ID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatorID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssuesForProject = `-- name: ListIssuesForProject :many
SELECT id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
FROM issues
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListIssuesForProject(ctx context.Context, projectID uuid.UUID) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatorID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForProjectByAssignee = `-- name: ListIssuesForProjectByAssignee :many
SELECT id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
FROM issues
WHERE project_id = $1 AND assignee_id = $2
ORDER BY created_at DESC, id DESC
`

type ListIssuesForProjectByAssigneeParams struct {
	ProjectID  uuid.UUID
	AssigneeID pgtype.UUID
}

func (q *Queries) ListIssuesForProjectByAssignee(ctx context.Context, arg ListIssuesForProjectByAssigneeParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesForProjectByAssignee, arg.ProjectID, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatorID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForProjectByStatus = `-- name: ListIssuesForProjectByStatus :many
SELECT id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
FROM issues
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC, id DESC
`

type ListIssuesForProjectByStatusParams struct {
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) ListIssuesForProjectByStatus(ctx context.Context, arg ListIssuesForProjectByStatusParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesForProjectByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatorID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForProjectByStatusAndAssignee = `-- name: ListIssuesForProjectByStatusAndAssignee :many
SELECT id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
FROM issues
WHERE project_id = $1 AND status = $2 AND assignee_id = $3
ORDER BY created_at DESC, id DESC
`

type ListIssuesForProjectByStatusAndAssigneeParams struct {
	ProjectID  uuid.UUID
	Status     string
	AssigneeID pgtype.UUID
}

func (q *Queries) ListIssuesForProjectByStatusAndAssignee(ctx context.Context, arg ListIssuesForProjectByStatusAndAssigneeParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesForProjectByStatusAndAssignee, arg.ProjectID, arg.Status, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.CreatorID,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues
SET title = $3,
    description = $4,
    status = $5,
    priority = $6,
    assignee_id = $7,
    updated_at = now()
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, title, description, status, priority, creator_id, assignee_id, created_at, updated_at
`

type UpdateIssueParams struct {
	ProjectID   uuid.UUID
	ID          uuid.UUID
	Title       string
	Description string
	Status      string
	Priority    string
	AssigneeID  pgtype.UUID
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.ProjectID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatorID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
