// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, slug, description, archived, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Slug        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, workspace_id, name, slug, description, archived, created_at, updated_at
FROM projects
WHERE workspace_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	WorkspaceID uuid.UUID
	Slug        string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.WorkspaceID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsForWorkspace = `-- name: ListProjectsForWorkspace :many
SELECT id, workspace_id, name, slug, description, archived, created_at, updated_at
FROM projects
WHERE workspace_id = $1
ORDER BY archived, created_at, id
`

func (q *Queries) ListProjectsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, slug = $4, description = $5, archived = $6, updated_at = now()
WHERE workspace_id = $1 AND slug = $2
RETURNING id, workspace_id, name, slug, description, archived, created_at, updated_at
`

type UpdateProjectParams struct {
	WorkspaceID uuid.UUID
	Slug        string
	Name        string
	Slug_2      string
	Description string
	Archived    bool
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.WorkspaceID,
		arg.Slug,
		arg.Name,
		arg.Slug_2,
		arg.Description,
		arg.Archived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
