// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name string
	Slug string
}

type CreateWorkspaceRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug)
	var i CreateWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role, added_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING workspace_id, user_id, role, added_by_user_id, created_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Role          WorkspaceRole
	AddedByUserID pgtype.UUID
}

type CreateWorkspaceMemberRow struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Role          WorkspaceRole
	AddedByUserID pgtype.UUID
	CreatedAt     time.Time
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (CreateWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.AddedByUserID,
	)
	var i CreateWorkspaceMemberRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :execrows
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findWorkspaceUserByEmail = `-- name: FindWorkspaceUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) FindWorkspaceUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findWorkspaceUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceForMember = `-- name: GetWorkspaceForMember :one
SELECT w.id, w.name, w.slug, w.created_at, w.updated_at, wm.role
FROM workspaces AS w
JOIN workspace_members AS wm ON wm.workspace_id = w.id
WHERE w.id = $1 AND wm.user_id = $2
`

type GetWorkspaceForMemberParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetWorkspaceForMemberRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      WorkspaceRole
}

func (q *Queries) GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (GetWorkspaceForMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForMember, arg.ID, arg.UserID)
	var i GetWorkspaceForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, added_by_user_id, created_at
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type GetWorkspaceMemberRow struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Role          WorkspaceRole
	AddedByUserID pgtype.UUID
	CreatedAt     time.Time
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT u.id, u.email, u.name, wm.role, wm.added_by_user_id, adder.name AS added_by_name, wm.created_at
FROM workspace_members AS wm
JOIN users AS u ON u.id = wm.user_id
LEFT JOIN users AS adder ON adder.id = wm.added_by_user_id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at, u.id
`

type ListWorkspaceMembersRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	Role          WorkspaceRole
	AddedByUserID pgtype.UUID
	AddedByName   pgtype.Text
	CreatedAt     time.Time
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AddedByUserID,
			&i.AddedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.created_at, w.updated_at, wm.role
FROM workspaces AS w
JOIN workspace_members AS wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1
ORDER BY w.created_at, w.id
`

type ListWorkspacesForUserRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      WorkspaceRole
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesForUserRow
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, user_id, role, added_by_user_id, created_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        WorkspaceRole
}

type UpdateWorkspaceMemberRoleRow struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Role          WorkspaceRole
	AddedByUserID pgtype.UUID
	CreatedAt     time.Time
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (UpdateWorkspaceMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i UpdateWorkspaceMemberRoleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at
`

type UpdateWorkspaceNameParams struct {
	ID   uuid.UUID
	Name string
}

type UpdateWorkspaceNameRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (UpdateWorkspaceNameRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceName, arg.ID, arg.Name)
	var i UpdateWorkspaceNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
